In [1]:
#import relevant pavckhages
import pandas as pd
import numpy as np

In [2]:
### https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html #for usecols to load cohort

df_cohort_step_4 = pd.read_csv("cohort_step_2.csv", usecols=["stay_id", "intime"])

df_cohort_step_4

        stay_id               intime
0      37067082  2157-11-20 19:18:02
1      31205490  2110-04-11 15:52:22
2      37510196  2131-01-11 04:20:05
3      39060235  2160-05-18 10:00:53
4      33685454  2129-08-04 12:45:00
...         ...                  ...
40452  37364566  2162-08-16 05:48:32
40453  32336619  2148-11-19 14:23:43
40454  36075953  2149-01-08 18:12:00
40455  38978960  2164-09-12 09:26:28
40456  36195440  2145-11-02 22:59:00

[40457 rows x 2 columns]

In [3]:
#checking after converting intime
df_cohort_step_4["intime"] = pd.to_datetime(df_cohort_step_4["intime"])

df_cohort_step_4["intime"].dtype

dtype('<M8[us]')

In [4]:
#defining stay_id set for filtering
cohort_stay_ids = set(df_cohort_step_4["stay_id"])

cohort_stay_ids

{31326208,
 39059460,
 38141957,
 30146566,
 35258379,
 39452683,
 32768012,
 34340881,
 39583761,
 32768025,
 31719450,
 34865181,
 38797343,
 33947679,
 36569119,
 35520548,
 37093416,
 35782697,
 39714859,
 33816624,
 37355570,
 36831286,
 33685560,
 35651641,
 34734140,
 34734146,
 31326279,
 37224523,
 38010956,
 36044877,
 33292366,
 33816659,
 34472023,
 31588440,
 33816664,
 33423447,
 31064157,
 35520609,
 33816676,
 39452777,
 33554544,
 33423472,
 36044915,
 34078836,
 37748857,
 38404217,
 34472060,
 34996349,
 31850631,
 38404233,
 30146698,
 34734219,
 34603150,
 36176022,
 39714969,
 32768155,
 37224605,
 38535327,
 34865314,
 39190690,
 32374950,
 32374951,
 35520679,
 38797478,
 34603182,
 33554608,
 35913905,
 35651760,
 34996407,
 34865335,
 37224633,
 38273210,
 39321789,
 35127491,
 34996424,
 35913928,
 39715020,
 32637139,
 33947864,
 37880029,
 33161440,
 33816801,
 37355746,
 39977184,
 30408933,
 34078953,
 35651817,
 35782889,
 37224689,
 32637171,
 37748979,
 34472183,
 36438264,
 38797570,
 37224709,
 30408968,
 32506122,
 36307211,
 31588620,
 39715089,
 33554709,
 36438293,
 37486870,
 30802202,
 39846170,
 38535456,
 33030439,
 32506152,
 36176169,
 38404395,
 33816878,
 39977263,
 38273332,
 30277942,
 35914038,
 36569401,
 37355834,
 36962620,
 35389758,
 31981888,
 38011202,
 31588674,
 39059780,
 32899396,
 31326534,
 34996554,
 35127634,
 37880149,
 33816926,
 33816940,
 38404461,
 37093744,
 39321969,
 38535541,
 33816950,
 31850870,
 38011269,
 31588751,
 31064463,
 30671255,
 31457690,
 37355931,
 36307355,
 31850910,
 34996638,
 35651999,
 36569505,
 33292712,
 36438446,
 39059889,
 34603446,
 32244151,
 38797751,
 30015933,
 33685949,
 32637375,
 30278082,
 39715273,
 31719887,
 37093845,
 35914200,
 36831708,
 39846365,
 39322080,
 38666720,
 36176359,
 38928875,
 34341359,
 34079218,
 32375282,
 31195638,
 36307451,
 39977468,
 38273537,
 34341380,
 32506377,
 30016009,
 37487113,
 36700682,
 30016014,
 34341391,
 36831759,
 33686033,
 38404624,
 31064598,
 35914263,
 36569622,
 35914264,
 30016026,
 35127830,
 38011424,
 34734627,
 30409252,
 38928931,
 34865702,
 31195694,
 35127859,
 33817140,
 34472501,
 36569652,
 30671418,
 36831809,
 36307525,
 36176454,
 33030731,
 33686105,
 32375386,
 31588956,
 30802524,
 35783263,
 30802539,
 34210414,
 31982192,
 33030769,
 34210425,
 38929019,
 33686141,
 30933632,
 33292933,
 39715466,
 32899729,
 34865817,
 31851162,
 38666908,
 33161888,
 38797985,
 31720098,
 30802595,
 34996899,
 39060133,
 37094054,
 39977638,
 34865830,
 35127974,
 37880486,
 30933677,
 35521202,
 32113332,
 30147256,
 31589049,
 38798019,
 33424068,
 31457994,
 34341582,
 36438735,
 30933712,
 35128014,
 31851222,
 33161942,
 39846616,
 31195872,
 31326955,
 36569840,
 37749490,
 31195898,
 38667004,
 30147329,
 33817347,
 30016265,
 32637706,
 39060235,
 34341646,
 31195920,
 35128082,
 32244501,
 36045590,
 39191319,
 34079516,
 39453471,
 30147362,
 34997026,
 37356325,
 39846697,
 35652393,
 39060277,
 38667061,
 37618485,
 37487417,
 37094208,
 39977793,
 35521347,
 37487427,
 30540615,
 38273864,
 30802766,
 38011728,
 35390291,
 33948500,
 31064919,
 38798172,
 32506717,
 34997086,
 33948512,
 35259239,
 39322474,
 30671724,
 30802797,
 39584622,
 37225327,
 34603889,
 33424246,
 35128182,
 39322489,
 30016383,
 38667136,
 30933888,
 34866058,
 32506767,
 39977872,
 37225361,
 31196048,
 36832149,
 39584665,
 36963228,
 33555356,
 36045726,
 31982495,
 31327141,
 38536103,
 39453608,
 36570025,
 35128235,
 34210732,
 38011822,
 36045744,
 33686449,
 36832182,
 33293242,
 37880762,
 36963264,
 33555392,
 38405058,
 36963268,
 38273992,
 39453641,
 31589327,
 36832210,
 36570066,
 38929363,
 34866137,
 36832217,
 30409691,
 35783644,
 37356513,
 37487585,
 33686502,
 37749734,
 37618669,
 30147565,
 30802926,
 39977970,
 39977971,
 34341876,
 35128311,
 36045816,
 36307963,
 37749758,
 38405119,
 36176896,
 31065091,
 36963332,
 30671875,
 37618693,
 30802952,
 39846922,
 34997263,
 33555473,
 38142994,
 34997265,
 30671892,
 37618708,
 39060500,
 31589402,
 36832288,
 30540834,
 30802983,
 34997294,
 38536239,
 33948720,
 31720499,
 34997302,
 37749820,
 31327294,
 37356607,
 37356610,
 32900167,
 39978063,
 37356629,
 37880922,
 34997342,
 32769122,
 35914850,
 33948774,
 30934119,
 35390569,
 31458416,
 34735222,
 31196279,
 39584892,
 32638077,
 33817725,
 31196291,
 33162373,
 36570249,
 37225623,
 35128473,
 35914909,
 35783849,
 32375981,
 34342062,
 34079918,
 36963501,
 33424558,
 35652787,
 32375988,
 39847091,
 33293498,
 31982779,
 30409916,
 34735293,
 33031359,
 31589568,
 32769218,
 36439238,
 34473160,
 31065288,
 35521736,
 34211020,
 34079949,
 38274256,
 36177104,
 30147796,
 38929622,
 32638169,
 39322846,
 38143199,
 39978206,
 39978210,
 32900337,
 35783922,
 31196409,
 36046073,
 33424637,
 35783935,
 31458566,
 37618961,
 37356819,
 35259675,
 30278944,
 37094692,
 33686823,
 37487912,
 39453994,
 37618998,
 33817918,
 30934338,
 31327555,
 30672196,
 34866500,
 39060806,
 37619014,
 36439369,
 30016843,
 34080078,
 30934354,
 39978323,
 34735447,
 32376156,
 30934365,
 31720799,
 36570472,
 31720814,
 34473327,
 32900464,
 36177262,
 39978352,
 30147954,
 37881209,
 36570489,
 39847290,
 35521915,
 30279037,
 36308350,
 35652992,
 39978369,
 30541193,
 38143370,
 33817997,
 37225870,
 31982993,
 31720850,
 31196567,
 39978391,
 32507299,
 31327652,
 30410157,
 37356974,
 35521972,
 31983030,
 37225911,
 35653046,
 35128759,
 33818040,
 37619131,
 32245180,
 39847356,
 38536639,
 30934471,
 38929863,
 31458761,
 34604492,
 31983052,
 39323086,
 33818062,
 34473424,
 38405585,
 34342355,
 35522003,
 35653078,
 31589850,
 31196635,
 37881315,
 33555940,
 36701671,
 32114152,
 31458793,
 32376305,
 37750260,
 39585270,
 33555960,
 34866687,
 34473473,
 39323144,
 33424907,
 31983116,
 35653143,
 38012439,
 37226012,
 30934559,
 30541346,
 31327779,
 38405668,
 35915310,
 30934574,
 33162817,
 38143557,
 34473541,
 32114247,
 39323207,
 30148170,
 32376395,
 37750349,
 31196754,
 33031766,
 38798937,
 31721051,
 34342494,
 39585377,
 31458920,
 37226091,
 34997867,
 32114285,
 31590000,
 33818226,
 32769654,
 33818238,
 35653249,
 30541444,
 35260056,
 36046489,
 39061148,
 31852193,
 37357219,
 31196836,
 38536869,
 39978664,
 34604713,
 38143658,
 36832945,
 36439730,
 38012595,
 34211509,
 30803639,
 36439742,
 32114371,
 39454408,
 30672585,
 33294029,
 35391186,
 31852243,
 31459030,
 30148311,
 36046550,
 30934747,
 32114396,
 32507614,
 30803679,
 38405856,
 31852255,
 35391202,
 32900830,
 37619431,
 39061223,
 34735850,
 33818347,
 37881579,
 38405871,
 30934771,
 34604788,
 34998005,
 33949434,
 34998011,
 34998010,
 39323401,
 36570890,
 30410511,
 38012689,
 37488401,
 35129107,
 33031956,
 32376597,
 37357335,
 37750552,
 32376604,
 31328028,
 33031972,
 33031990,
 35129147,
 30148413,
 38537021,
 37488447,
 39585600,
 34080576,
 32900932,
 37357381,
 38930248,
 31197007,
 37619539,
 36308820,
 31983448,
 39323481,
 30541660,
 31590237,
 39716702,
 37488486,
 30279527,
 33949545,
 34998122,
 36046701,
 36833135,
 34473853,
 35260297,
 33163149,
 36833167,
 38930324,
 35653525,
 31066010,
 38406042,
 33032093,
 35260324,
 32245674,
 31983533,
 30934957,
 34867123,
 38275000,
 31983544,
 39716792,
 38275003,
 36833212,
 38668223,
 31721409,
 33818563,
 36833225,
 36046796,
 37881806,
 38537173,
 32245718,
 31590357,
 37750747,
 33425373,
 36046816,
 32770017,
 37750755,
 39716835,
 31852517,
 39061477,
 39585771,
 32376811,
 32114670,
 35653618,
 36046835,
 34867190,
 30279677,
 33425416,
 32770057,
 31983626,
 38668299,
 33687571,
 38275092,
 39192601,
 35915802,
 32114713,
 38144029,
 38012958,
 31328287,
 39979040,
 37488674,
 30017572,
 33425449,
 30672939,
 32770095,
 39454771,
 34342967,
 32114752,
 36964418,
 39061571,
 36440132,
 34998351,
 33294418,
 34736210,
 35784790,
 37488735,
 39454818,
 31983721,
 32114795,
 31721587,
 30935155,
 38144115,
 32901251,
 34343050,
 33687693,
 36178061,
 33425551,
 34605200,
 32639121,
 30804114,
 35653781,
 39585945,
 36833437,
 35129503,
 38144159,
 37750953,
 35653802,
 32377004,
 33556656,
 32901301,
 31197366,
 37095609,
 31459516,
 34605253,
 32508102,
 32508103,
 33425608,
 34867401,
 38930634,
 33163467,
 33425610,
 32770253,
 36047053,
 34998479,
 35391696,
 31328473,
 31852765,
 31852766,
 32508125,
 33949923,
 39454950,
 36571367,
 34605291,
 32770290,
 37751027,
 34867442,
 33818869,
 33425658,
 36571388,
 37357821,
 33032447,
 31066370,
 33687816,
 38930700,
 32901390,
 34605328,
 32508180,
 33163546,
 31721758,
 36047137,
 37751073,
 39323941,
 32901414,
 34474280,
 31590699,
 39455024,
 35391794,
 34736434,
 39717184,
 31590722,
 34081091,
 31721798,
 36833608,
 32901451,
 33032524,
 32639313,
 33950034,
 35916115,
 38013272,
 34081112,
 30804316,
 37226845,
 30542175,
 39717215,
 30280038,
 36964710,
 34867560,
 34212201,
 37620076,
 39586165,
 38930808,
 31590777,
 38144386,
 30673285,
 34081158,
 33163655,
 34081159,
 39586196,
 38930846,
 38930850,
 37751211,
 30935470,
 32770480,
 31984049,
 38406578,
 35916210,
 32770497,
 38930887,
 31328712,
 33688017,
 38930899,
 32115156,
 37095898,
 33819113,
 37751275,
 39979502,
 31590895,
 37226992,
 34867699,
 39062004,
 30018043,
 33032699,
 32377341,
 30018045,
 36440578,
 39848457,
 30542348,
 36047376,
 37489172,
 32770582,
 36833816,
 35654172,
 36833820,
 32770592,
 37489187,
 34736678,
 31066662,
 31459880,
 33294890,
 34605615,
 37882416,
 38537777,
 33819188,
 31984182,
 36964919,
 32246328,
 31328826,
 37620283,
 35392063,
 33032768,
 33032770,
 36178498,
 32770627,
 39979589,
 34212419,
 32115271,
 39193160,
 31197768,
 36309571,
 31066699,
 35654221,
 39586382,
 38013526,
 36178521,
 32246363,
 37882463,
 32770663,
 39586409,
 35261038,
 32115315,
 35392118,
 34736760,
 33557113,
 32115323,
 36702850,
 34343559,
 36571787,
 36309643,
 33294987,
 30149263,
 32377490,
 31853205,
 33163929,
 30149278,
 38931105,
 39717538,
 33950371,
 34474657,
 32377509,
 39324322,
 32377519,
 36965043,
 30804660,
 38537911,
 31197883,
 35392191,
 35523269,
 32508625,
 31328982,
 37620444,
 30018269,
 36440800,
 37489377,
 36178658,
 31591142,
 39586534,
 36047592,
 36702954,
 36178670,
 31460081,
 35261170,
 33164021,
 33688323,
 36702983,
 36309769,
 34867980,
 31853325,
 30804751,
 38800147,
 30280467,
 37227290,
 38275869,
 32115488,
 36571939,
 33557284,
 39193383,
 38800171,
 38406956,
 31984434,
 32115509,
 31460150,
 38144823,
 34081592,
 33295159,
 32639802,
 33950521,
 33295162,
 36178749,
 38144830,
 34868030,
 33688389,
 39586629,
 36571976,
 33688395,
 32639820,
 32508751,
 33688419,
 36834149,
 38407017,
 30673770,
 33557357,
 37096309,
 35130229,
 35916663,
 30542714,
 31984510,
 36572031,
 36309888,
 31722369,
 33950594,
 31067011,
 36178821,
 39586693,
 30542728,
 36178826,
 34212747,
 38669202,
 36572050,
 38669203,
 39193495,
 34212764,
 30411691,
 31198125,
 36047797,
 ...}

In [5]:
### https://gist.github.com/cengizhancaliskan/e2aff781378793454b7615cb02745fc7
#reading in chunks and filtering by stay_id

filename = "/Users/abdullahhasib/Library/CloudStorage/OneDrive-SharedLibraries-NationalUniversityofSingapore/Ansel Lim - SPH6004_group/data/MIMIC-IV-time_series(Group Assignment).csv"
chunksize = 10 ** 6
chunk_list = []

for chunk in pd.read_csv(filename, chunksize=chunksize, na_values="NULL"):
    chunk = chunk[chunk["stay_id"].isin(cohort_stay_ids)]
    chunk_list.append(chunk)

df_ts = pd.concat(chunk_list, ignore_index=True)
del chunk_list

df_ts

,stay_id,hour_ts,hr,map,rr,spo2,temp,gcs,lactate,creatinine,...,urine_output,vasopressor_dose,fluid_input,ventilation_flag,sofa_resp,sofa_cardio,sofa_renal,sofa_liver,sofa_coag,sofa_cns
0,30000153,2174-09-29 12:00:00,100.0,8.0,18.0,NaN,96.8,1.0,NaN,NaN,...,280.0,NaN,NaN,1,NaN,0.0,NaN,NaN,NaN,0.0
1,30000153,2174-09-29 13:00:00,104.0,NaN,16.0,NaN,NaN,NaN,1.3,NaN,...,NaN,NaN,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN
2,30000153,2174-09-29 14:00:00,83.0,NaN,16.0,NaN,99.1,NaN,2.1,NaN,...,745.0,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN
3,30000153,2174-09-29 15:00:00,92.0,8.0,14.0,NaN,NaN,NaN,NaN,0.9,...,50.0,NaN,NaN,0,NaN,0.0,0.0,NaN,0.0,NaN
4,30000153,2174-09-29 16:00:00,83.0,NaN,16.0,NaN,99.5,1.0,NaN,NaN,...,50.0,NaN,NaN,0,0.0,0.0,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4000708,39999552,2186-07-18 14:00:00,74.0,NaN,28.0,NaN,NaN,NaN,NaN,NaN,...,225.0,NaN,NaN,0,NaN,0.0,0.0,NaN,NaN,NaN
4000709,39999552,2186-07-18 15:00:00,71.0,NaN,16.0,NaN,NaN,NaN,NaN,NaN,...,325.0,NaN,NaN,0,NaN,0.0,0.0,NaN,NaN,NaN
4000710,39999552,2186-07-18 16:00:00,73.0,NaN,14.0,NaN,NaN,4.0,NaN,NaN,...,300.0,NaN,NaN,0,NaN,0.0,0.0,NaN,NaN,0.0
4000711,39999552,2186-07-18 17:00:00,75.0,NaN,22.0,NaN,NaN,NaN,NaN,NaN,...,140.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4000712,39999552,2186-07-18 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Reference: https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html

# changing hour_ts to datetime for calculation
df_ts["hour_ts"] = pd.to_datetime(df_ts["hour_ts"])

df_ts["hour_ts"].dtype

dtype('<M8[us]')

In [7]:
# merging df_ts with df_cohort_step_4 to get intime for each stay_id
df_ts = df_ts.merge(df_cohort_step_4[["stay_id", "intime"]], on="stay_id", how="left")

df_ts.head()

,stay_id,hour_ts,hr,map,rr,spo2,temp,gcs,lactate,creatinine,...,vasopressor_dose,fluid_input,ventilation_flag,sofa_resp,sofa_cardio,sofa_renal,sofa_liver,sofa_coag,sofa_cns,intime
0,30000153,2174-09-29 12:00:00,100.0,8.0,18.0,NaN,96.8,1.0,NaN,NaN,...,NaN,NaN,1,NaN,0.0,NaN,NaN,NaN,0.0,2174-09-29 12:09:00
1,30000153,2174-09-29 13:00:00,104.0,NaN,16.0,NaN,NaN,NaN,1.3,NaN,...,NaN,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN,2174-09-29 12:09:00
2,30000153,2174-09-29 14:00:00,83.0,NaN,16.0,NaN,99.1,NaN,2.1,NaN,...,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,2174-09-29 12:09:00
3,30000153,2174-09-29 15:00:00,92.0,8.0,14.0,NaN,NaN,NaN,NaN,0.9,...,NaN,NaN,0,NaN,0.0,0.0,NaN,0.0,NaN,2174-09-29 12:09:00
4,30000153,2174-09-29 16:00:00,83.0,NaN,16.0,NaN,99.5,1.0,NaN,NaN,...,NaN,NaN,0,0.0,0.0,NaN,NaN,NaN,0.0,2174-09-29 12:09:00

In [8]:
#converting hour_ts and intime by 3600 to get relative hour
df_ts["relative_hour"] = (
    df_ts["hour_ts"] - df_ts["intime"]
).dt.total_seconds() / 3600

df_ts.head()

,stay_id,hour_ts,hr,map,rr,spo2,temp,gcs,lactate,creatinine,...,fluid_input,ventilation_flag,sofa_resp,sofa_cardio,sofa_renal,sofa_liver,sofa_coag,sofa_cns,intime,relative_hour
0,30000153,2174-09-29 12:00:00,100.0,8.0,18.0,NaN,96.8,1.0,NaN,NaN,...,NaN,1,NaN,0.0,NaN,NaN,NaN,0.0,2174-09-29 12:09:00,-0.15
1,30000153,2174-09-29 13:00:00,104.0,NaN,16.0,NaN,NaN,NaN,1.3,NaN,...,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN,2174-09-29 12:09:00,0.85
2,30000153,2174-09-29 14:00:00,83.0,NaN,16.0,NaN,99.1,NaN,2.1,NaN,...,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,2174-09-29 12:09:00,1.85
3,30000153,2174-09-29 15:00:00,92.0,8.0,14.0,NaN,NaN,NaN,NaN,0.9,...,NaN,0,NaN,0.0,0.0,NaN,0.0,NaN,2174-09-29 12:09:00,2.85
4,30000153,2174-09-29 16:00:00,83.0,NaN,16.0,NaN,99.5,1.0,NaN,NaN,...,NaN,0,0.0,0.0,NaN,NaN,NaN,0.0,2174-09-29 12:09:00,3.85

In [9]:
#dropping hour_ts and intime
df_ts = df_ts.drop(columns=["hour_ts", "intime"])

df_ts["relative_hour"].describe()

count    4.000713e+06
mean     1.295225e+02
std      1.901826e+02
min     -9.997222e-01
25%      2.372333e+01
50%      5.975000e+01
75%      1.558336e+02
max      2.645517e+03
Name: relative_hour, dtype: float64

In [ ]:
# keeping only data within observation window [-3h to +24h]

df_ts_window = df_ts[(df_ts["relative_hour"] >= -3) & (df_ts["relative_hour"] <= 24)].copy()

#checking before and after filtering by observation window
print(f"Before filter : {len(df_ts):,} rows")
print(f"After filter  : {len(df_ts_window):,} rows")
print(f"Unique stays  : {df_ts_window['stay_id'].nunique():,}")

Before filter : 4,000,713 rows
After filter  : 1,011,425 rows
Unique stays  : 40,457

In [11]:
### https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isnull.html
#Determining which variables are dense vs sparse based on coverage
#checking how often each variable is measured

coverage = df_ts_window.notna().mean() * 100

coverage

stay_id             100.000000
hr                   93.704328
map                   9.211360
rr                   93.208394
spo2                  0.000000
temp                 30.401760
gcs                  30.918061
lactate               8.200608
creatinine            9.152335
bilirubin             2.500729
platelets             9.028944
wbc                   0.622290
sodium               11.329362
bun                   8.971204
inr                   0.000000
urine_output         60.815977
vasopressor_dose      9.926984
fluid_input           1.394567
ventilation_flag    100.000000
sofa_resp             6.137380
sofa_cardio          88.385397
sofa_renal           13.171417
sofa_liver            2.479571
sofa_coag             8.425340
sofa_cns             30.661492
relative_hour       100.000000
dtype: float64

In [12]:
# sorting the variables based on frequency 

coverage.sort_values(ascending=False)

stay_id             100.000000
ventilation_flag    100.000000
relative_hour       100.000000
hr                   93.704328
rr                   93.208394
sofa_cardio          88.385397
urine_output         60.815977
gcs                  30.918061
sofa_cns             30.661492
temp                 30.401760
sofa_renal           13.171417
sodium               11.329362
vasopressor_dose      9.926984
map                   9.211360
creatinine            9.152335
platelets             9.028944
bun                   8.971204
sofa_coag             8.425340
lactate               8.200608
sofa_resp             6.137380
bilirubin             2.500729
sofa_liver            2.479571
fluid_input           1.394567
wbc                   0.622290
spo2                  0.000000
inr                   0.000000
dtype: float64

In [13]:
# classifying variables based on coverage
# dense  = coverage > 50%
# sparse = coverage <= 50%

DENSE_VARS  = ["ventilation_flag", "hr", "rr", "sofa_cardio", "urine_output"]


SPARSE_VARS = ["gcs", "sofa_cns", "temp", "sofa_renal", "sodium", "vasopressor_dose", "map",  
               "creatinine", "platelets", "bun", "sofa_coag", "lactate", "sofa_resp", "bilirubin",
               "sofa_liver", "fluid_input", "wbc"]

#dropping spo2 and intr as they are 0 
df_ts_window = df_ts_window.drop(columns=["spo2", "inr"], errors="ignore")

df_ts_window.columns

Index(['stay_id', 'hr', 'map', 'rr', 'temp', 'gcs', 'lactate', 'creatinine',
       'bilirubin', 'platelets', 'wbc', 'sodium', 'bun', 'urine_output',
       'vasopressor_dose', 'fluid_input', 'ventilation_flag', 'sofa_resp',
       'sofa_cardio', 'sofa_renal', 'sofa_liver', 'sofa_coag', 'sofa_cns',
       'relative_hour'],
      dtype='str')

In [14]:
# defining slope function to measure variable trend as clinically important
# slope > 0 = increasing, slope < 0 = decreasing
# Reference: https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html

def slope(series):
    valid = series.dropna()
    if len(valid) < 2:
        return np.nan
    x = np.arange(len(valid))
    return np.polyfit(x, valid.values, 1)[0]

In [15]:
#dense variable aggregation with 7 statistical features (mean, min, max, std, last value, count, slope)
#aggregating heart rate
hr_agg = df_ts_window.groupby("stay_id")["hr"].agg(
    hr_mean="mean",
    hr_min="min",
    hr_max="max",
    hr_std="std",
    hr_last="last",
    hr_count="count"
).reset_index()

hr_agg["hr_slope"] = df_ts_window.groupby("stay_id")["hr"].apply(slope).values

hr_agg.head()

,stay_id,hr_mean,hr_min,hr_max,hr_std,hr_last,hr_count,hr_slope
0,30000153,106.040000,83.0,128.0,12.084701,90.0,25,0.093846
1,30000646,84.090000,69.0,102.0,9.619013,80.5,25,-0.587308
2,30001148,74.909091,64.0,80.0,5.639226,64.0,22,-0.635799
3,30001336,63.041667,53.0,73.0,5.689267,68.0,24,0.273913
4,30001396,83.583333,74.0,93.0,4.262237,85.0,24,0.055652

In [16]:
# adding binary column for whether heart rate was once measured during the observation window 

hr_agg["hr_measured"] = (hr_agg["hr_count"] > 0).astype(int)

hr_agg.head()

,stay_id,hr_mean,hr_min,hr_max,hr_std,hr_last,hr_count,hr_slope,hr_measured
0,30000153,106.040000,83.0,128.0,12.084701,90.0,25,0.093846,1
1,30000646,84.090000,69.0,102.0,9.619013,80.5,25,-0.587308,1
2,30001148,74.909091,64.0,80.0,5.639226,64.0,22,-0.635799,1
3,30001336,63.041667,53.0,73.0,5.689267,68.0,24,0.273913,1
4,30001396,83.583333,74.0,93.0,4.262237,85.0,24,0.055652,1

In [17]:
# aggregating respiratory rate

rr_agg = df_ts_window.groupby("stay_id")["rr"].agg(
    rr_mean="mean",
    rr_min="min",
    rr_max="max",
    rr_std="std",
    rr_last="last",
    rr_count="count"
).reset_index()

rr_agg["rr_slope"] = df_ts_window.groupby("stay_id")["rr"].apply(slope).values

rr_agg.head()

    stay_id    rr_mean  rr_min  rr_max    rr_std  rr_last  rr_count  rr_slope
0  30000153  15.020000    10.0    22.0  3.781754     10.0        25 -0.283846
1  30000646  23.037619    15.0    33.0  5.669963     16.0        25 -0.299551
2  30001148  15.083333     7.0    23.0  4.233511     21.0        22  0.290890
3  30001336  25.820000    18.0    33.0  4.120275     33.0        25  0.201923
4  30001396  22.708333    19.0    28.0  2.835783     20.0        24  0.136957

In [18]:
# adding binary column for whether heart rate was once measured during the observation window 

rr_agg["rr_measured"] = (rr_agg["rr_count"] > 0).astype(int)

rr_agg.head()

,stay_id,rr_mean,rr_min,rr_max,rr_std,rr_last,rr_count,rr_slope,rr_measured
0,30000153,15.020000,10.0,22.0,3.781754,10.0,25,-0.283846,1
1,30000646,23.037619,15.0,33.0,5.669963,16.0,25,-0.299551,1
2,30001148,15.083333,7.0,23.0,4.233511,21.0,22,0.290890,1
3,30001336,25.820000,18.0,33.0,4.120275,33.0,25,0.201923,1
4,30001396,22.708333,19.0,28.0,2.835783,20.0,24,0.136957,1

In [19]:
#merging them based on stay_id
df_dense_agg = hr_agg.merge(rr_agg, on="stay_id", how="left")

df_dense_agg.head()

,stay_id,hr_mean,hr_min,hr_max,hr_std,hr_last,hr_count,hr_slope,hr_measured,rr_mean,rr_min,rr_max,rr_std,rr_last,rr_count,rr_slope,rr_measured
0,30000153,106.040000,83.0,128.0,12.084701,90.0,25,0.093846,1,15.020000,10.0,22.0,3.781754,10.0,25,-0.283846,1
1,30000646,84.090000,69.0,102.0,9.619013,80.5,25,-0.587308,1,23.037619,15.0,33.0,5.669963,16.0,25,-0.299551,1
2,30001148,74.909091,64.0,80.0,5.639226,64.0,22,-0.635799,1,15.083333,7.0,23.0,4.233511,21.0,22,0.290890,1
3,30001336,63.041667,53.0,73.0,5.689267,68.0,24,0.273913,1,25.820000,18.0,33.0,4.120275,33.0,25,0.201923,1
4,30001396,83.583333,74.0,93.0,4.262237,85.0,24,0.055652,1,22.708333,19.0,28.0,2.835783,20.0,24,0.136957,1

In [20]:
# aggregating ventilation flag

ventilation_agg = df_ts_window.groupby("stay_id")["ventilation_flag"].agg(
    ventilation_flag_mean="mean",
    ventilation_flag_min="min",
    ventilation_flag_max="max",
    ventilation_flag_std="std",
    ventilation_flag_last="last",
    ventilation_flag_count="count"
).reset_index()

ventilation_agg["ventilation_flag_slope"] = df_ts_window.groupby("stay_id")["ventilation_flag"].apply(slope).values

ventilation_agg.head()

,stay_id,ventilation_flag_mean,ventilation_flag_min,ventilation_flag_max,ventilation_flag_std,ventilation_flag_last,ventilation_flag_count,ventilation_flag_slope
0,30000153,0.08,0,1,0.276887,0,25,-0.012308
1,30000646,0.04,0,1,0.200000,0,25,-0.009231
2,30001148,0.04,0,1,0.200000,0,25,-0.003846
3,30001336,0.04,0,1,0.200000,0,25,-0.009231
4,30001396,0.04,0,1,0.200000,0,25,-0.007692

In [21]:
ventilation_agg["ventilation_flag_measured"] = (ventilation_agg["ventilation_flag_count"] > 0).astype(int)

ventilation_agg.head()

,stay_id,ventilation_flag_mean,ventilation_flag_min,ventilation_flag_max,ventilation_flag_std,ventilation_flag_last,ventilation_flag_count,ventilation_flag_slope,ventilation_flag_measured
0,30000153,0.08,0,1,0.276887,0,25,-0.012308,1
1,30000646,0.04,0,1,0.200000,0,25,-0.009231,1
2,30001148,0.04,0,1,0.200000,0,25,-0.003846,1
3,30001336,0.04,0,1,0.200000,0,25,-0.009231,1
4,30001396,0.04,0,1,0.200000,0,25,-0.007692,1

In [22]:
df_dense_agg = df_dense_agg.merge(ventilation_agg, on="stay_id", how="left")

df_dense_agg.head()

,stay_id,hr_mean,hr_min,hr_max,hr_std,hr_last,hr_count,hr_slope,hr_measured,rr_mean,...,rr_slope,rr_measured,ventilation_flag_mean,ventilation_flag_min,ventilation_flag_max,ventilation_flag_std,ventilation_flag_last,ventilation_flag_count,ventilation_flag_slope,ventilation_flag_measured
0,30000153,106.040000,83.0,128.0,12.084701,90.0,25,0.093846,1,15.020000,...,-0.283846,1,0.08,0,1,0.276887,0,25,-0.012308,1
1,30000646,84.090000,69.0,102.0,9.619013,80.5,25,-0.587308,1,23.037619,...,-0.299551,1,0.04,0,1,0.200000,0,25,-0.009231,1
2,30001148,74.909091,64.0,80.0,5.639226,64.0,22,-0.635799,1,15.083333,...,0.290890,1,0.04,0,1,0.200000,0,25,-0.003846,1
3,30001336,63.041667,53.0,73.0,5.689267,68.0,24,0.273913,1,25.820000,...,0.201923,1,0.04,0,1,0.200000,0,25,-0.009231,1
4,30001396,83.583333,74.0,93.0,4.262237,85.0,24,0.055652,1,22.708333,...,0.136957,1,0.04,0,1,0.200000,0,25,-0.007692,1

In [23]:
# aggregating urine output

urine_agg = df_ts_window.groupby("stay_id")["urine_output"].agg(
    urine_output_mean="mean",
    urine_output_min="min",
    urine_output_max="max",
    urine_output_std="std",
    urine_output_last="last",
    urine_output_count="count"
).reset_index()

urine_agg["urine_output_slope"] = df_ts_window.groupby("stay_id")["urine_output"].apply(slope).values

urine_agg.head()

,stay_id,urine_output_mean,urine_output_min,urine_output_max,urine_output_std,urine_output_last,urine_output_count,urine_output_slope
0,30000153,107.500000,25.0,745.0,169.343455,100.0,18,-13.730650
1,30000646,705.555556,0.0,1000.0,343.415241,975.0,9,57.916667
2,30001148,126.190476,25.0,480.0,105.010770,105.0,21,-6.214286
3,30001336,455.555556,350.0,750.0,117.777450,425.0,9,5.000000
4,30001396,400.000000,200.0,600.0,282.842712,200.0,2,-400.000000

In [24]:
urine_agg["urine_output_measured"] = (urine_agg["urine_output_count"] > 0).astype(int)

urine_agg.head()

,stay_id,urine_output_mean,urine_output_min,urine_output_max,urine_output_std,urine_output_last,urine_output_count,urine_output_slope,urine_output_measured
0,30000153,107.500000,25.0,745.0,169.343455,100.0,18,-13.730650,1
1,30000646,705.555556,0.0,1000.0,343.415241,975.0,9,57.916667,1
2,30001148,126.190476,25.0,480.0,105.010770,105.0,21,-6.214286,1
3,30001336,455.555556,350.0,750.0,117.777450,425.0,9,5.000000,1
4,30001396,400.000000,200.0,600.0,282.842712,200.0,2,-400.000000,1

In [25]:
df_dense_agg = df_dense_agg.merge(urine_agg, on="stay_id", how="left")

df_dense_agg.head()

,stay_id,hr_mean,hr_min,hr_max,hr_std,hr_last,hr_count,hr_slope,hr_measured,rr_mean,...,ventilation_flag_slope,ventilation_flag_measured,urine_output_mean,urine_output_min,urine_output_max,urine_output_std,urine_output_last,urine_output_count,urine_output_slope,urine_output_measured
0,30000153,106.040000,83.0,128.0,12.084701,90.0,25,0.093846,1,15.020000,...,-0.012308,1,107.500000,25.0,745.0,169.343455,100.0,18,-13.730650,1
1,30000646,84.090000,69.0,102.0,9.619013,80.5,25,-0.587308,1,23.037619,...,-0.009231,1,705.555556,0.0,1000.0,343.415241,975.0,9,57.916667,1
2,30001148,74.909091,64.0,80.0,5.639226,64.0,22,-0.635799,1,15.083333,...,-0.003846,1,126.190476,25.0,480.0,105.010770,105.0,21,-6.214286,1
3,30001336,63.041667,53.0,73.0,5.689267,68.0,24,0.273913,1,25.820000,...,-0.009231,1,455.555556,350.0,750.0,117.777450,425.0,9,5.000000,1
4,30001396,83.583333,74.0,93.0,4.262237,85.0,24,0.055652,1,22.708333,...,-0.007692,1,400.000000,200.0,600.0,282.842712,200.0,2,-400.000000,1

In [26]:
# aggregating sofa cardiovascular score

sofa_cardio_agg = df_ts_window.groupby("stay_id")["sofa_cardio"].agg(
    sofa_cardio_mean="mean",
    sofa_cardio_min="min",
    sofa_cardio_max="max",
    sofa_cardio_std="std",
    sofa_cardio_last="last",
    sofa_cardio_count="count"
).reset_index()

sofa_cardio_agg["sofa_cardio_slope"] = df_ts_window.groupby("stay_id")["sofa_cardio"].apply(slope).values

sofa_cardio_agg.head()

,stay_id,sofa_cardio_mean,sofa_cardio_min,sofa_cardio_max,sofa_cardio_std,sofa_cardio_last,sofa_cardio_count,sofa_cardio_slope
0,30000153,0.00000,0.0,0.0,0.000000,0.0,24,0.000000
1,30000646,0.72000,0.0,1.0,0.458258,1.0,25,0.014615
2,30001148,0.52381,0.0,1.0,0.511766,1.0,21,0.038961
3,30001336,0.62500,0.0,1.0,0.494535,0.0,24,-0.008261
4,30001396,0.00000,0.0,0.0,0.000000,0.0,23,0.000000

In [27]:
sofa_cardio_agg["sofa_cardio_measured"] = (sofa_cardio_agg["sofa_cardio_count"] > 0).astype(int)

sofa_cardio_agg.head()

,stay_id,sofa_cardio_mean,sofa_cardio_min,sofa_cardio_max,sofa_cardio_std,sofa_cardio_last,sofa_cardio_count,sofa_cardio_slope,sofa_cardio_measured
0,30000153,0.00000,0.0,0.0,0.000000,0.0,24,0.000000,1
1,30000646,0.72000,0.0,1.0,0.458258,1.0,25,0.014615,1
2,30001148,0.52381,0.0,1.0,0.511766,1.0,21,0.038961,1
3,30001336,0.62500,0.0,1.0,0.494535,0.0,24,-0.008261,1
4,30001396,0.00000,0.0,0.0,0.000000,0.0,23,0.000000,1

In [28]:
#all together in one final aggregated dataframe
df_dense_agg = df_dense_agg.merge(sofa_cardio_agg, on="stay_id", how="left")

df_dense_agg.head()

,stay_id,hr_mean,hr_min,hr_max,hr_std,hr_last,hr_count,hr_slope,hr_measured,rr_mean,...,urine_output_slope,urine_output_measured,sofa_cardio_mean,sofa_cardio_min,sofa_cardio_max,sofa_cardio_std,sofa_cardio_last,sofa_cardio_count,sofa_cardio_slope,sofa_cardio_measured
0,30000153,106.040000,83.0,128.0,12.084701,90.0,25,0.093846,1,15.020000,...,-13.730650,1,0.00000,0.0,0.0,0.000000,0.0,24,0.000000,1
1,30000646,84.090000,69.0,102.0,9.619013,80.5,25,-0.587308,1,23.037619,...,57.916667,1,0.72000,0.0,1.0,0.458258,1.0,25,0.014615,1
2,30001148,74.909091,64.0,80.0,5.639226,64.0,22,-0.635799,1,15.083333,...,-6.214286,1,0.52381,0.0,1.0,0.511766,1.0,21,0.038961,1
3,30001336,63.041667,53.0,73.0,5.689267,68.0,24,0.273913,1,25.820000,...,5.000000,1,0.62500,0.0,1.0,0.494535,0.0,24,-0.008261,1
4,30001396,83.583333,74.0,93.0,4.262237,85.0,24,0.055652,1,22.708333,...,-400.000000,1,0.00000,0.0,0.0,0.000000,0.0,23,0.000000,1

In [29]:
#checking final shape
df_dense_agg.shape

(40457, 41)

In [30]:
#aggregating sparse variables with 5 statistical features
#aggregating glasgow coma scale (gcs)
gcs_agg = df_ts_window.groupby("stay_id")["gcs"].agg(
    gcs_mean="mean",
    gcs_min="min",
    gcs_max="max",
    gcs_last="last",
    gcs_count="count"
).reset_index()

gcs_agg.head()

    stay_id  gcs_mean  gcs_min  gcs_max  gcs_last  gcs_count
0  30000153  2.647059      1.0      4.0       4.0         17
1  30000646  4.000000      4.0      4.0       4.0          4
2  30001148  2.833333      1.0      4.0       4.0          6
3  30001336  4.000000      4.0      4.0       4.0          3
4  30001396  3.500000      3.0      4.0       4.0          6

In [31]:
gcs_agg["gcs_measured"] = (gcs_agg["gcs_count"] > 0).astype(int)

gcs_agg.head()

    stay_id  gcs_mean  gcs_min  gcs_max  gcs_last  gcs_count  gcs_measured
0  30000153  2.647059      1.0      4.0       4.0         17             1
1  30000646  4.000000      4.0      4.0       4.0          4             1
2  30001148  2.833333      1.0      4.0       4.0          6             1
3  30001336  4.000000      4.0      4.0       4.0          3             1
4  30001396  3.500000      3.0      4.0       4.0          6             1

In [32]:
# aggregating temperature (temp)

temp_agg = df_ts_window.groupby("stay_id")["temp"].agg(
    temp_mean="mean",
    temp_min="min",
    temp_max="max",
    temp_last="last",
    temp_count="count"
).reset_index()

temp_agg.head()

    stay_id  temp_mean  temp_min  temp_max  temp_last  temp_count
0  30000153  99.162500      96.8     100.8       99.1           8
1  30000646  99.200000      97.8     102.4       98.0           9
2  30001148  97.500000      95.6     100.7      100.7           9
3  30001336  98.342857      98.1      98.5       98.4           7
4  30001396  99.371429      97.3     101.9       98.3           7

In [33]:
temp_agg["temp_measured"] = (temp_agg["temp_count"] > 0).astype(int)

temp_agg.head()

,stay_id,temp_mean,temp_min,temp_max,temp_last,temp_count,temp_measured
0,30000153,99.162500,96.8,100.8,99.1,8,1
1,30000646,99.200000,97.8,102.4,98.0,9,1
2,30001148,97.500000,95.6,100.7,100.7,9,1
3,30001336,98.342857,98.1,98.5,98.4,7,1
4,30001396,99.371429,97.3,101.9,98.3,7,1

In [34]:
df_sparse_agg = gcs_agg.merge(temp_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,temp_last,temp_count,temp_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,99.1,8,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,98.0,9,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,100.7,9,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,98.4,7,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,98.3,7,1

In [35]:
# aggregating mean arterial pressure (map)

map_agg = df_ts_window.groupby("stay_id")["map"].agg(
    map_mean="mean",
    map_min="min",
    map_max="max",
    map_last="last",
    map_count="count"
).reset_index()

map_agg.head()

    stay_id  map_mean  map_min  map_max  map_last  map_count
0  30000153  7.333333      6.0      8.0       6.0          3
1  30000646       NaN      NaN      NaN       NaN          0
2  30001148  7.000000      7.0      7.0       7.0          2
3  30001336       NaN      NaN      NaN       NaN          0
4  30001396       NaN      NaN      NaN       NaN          0

In [36]:
map_agg["map_measured"] = (map_agg["map_count"] > 0).astype(int)

map_agg.head()

    stay_id  map_mean  map_min  map_max  map_last  map_count  map_measured
0  30000153  7.333333      6.0      8.0       6.0          3             1
1  30000646       NaN      NaN      NaN       NaN          0             0
2  30001148  7.000000      7.0      7.0       7.0          2             1
3  30001336       NaN      NaN      NaN       NaN          0             0
4  30001396       NaN      NaN      NaN       NaN          0             0

In [37]:
df_sparse_agg = df_sparse_agg.merge(map_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,temp_last,temp_count,temp_measured,map_mean,map_min,map_max,map_last,map_count,map_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,99.1,8,1,7.333333,6.0,8.0,6.0,3,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,98.0,9,1,NaN,NaN,NaN,NaN,0,0
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,100.7,9,1,7.000000,7.0,7.0,7.0,2,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,98.4,7,1,NaN,NaN,NaN,NaN,0,0
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,98.3,7,1,NaN,NaN,NaN,NaN,0,0

In [38]:
# aggregating lactate

lactate_agg = df_ts_window.groupby("stay_id")["lactate"].agg(
    lactate_mean="mean",
    lactate_min="min",
    lactate_max="max",
    lactate_last="last",
    lactate_count="count"
).reset_index()

lactate_agg.head()

,stay_id,lactate_mean,lactate_min,lactate_max,lactate_last,lactate_count
0,30000153,1.700000,1.3,2.1,2.1,2
1,30000646,1.600000,1.6,1.6,1.6,2
2,30001148,1.500000,1.5,1.5,1.5,1
3,30001336,NaN,NaN,NaN,NaN,0
4,30001396,136.266667,1.8,220.0,220.0,3

In [39]:
lactate_agg["lactate_measured"] = (lactate_agg["lactate_count"] > 0).astype(int)

lactate_agg.head()

,stay_id,lactate_mean,lactate_min,lactate_max,lactate_last,lactate_count,lactate_measured
0,30000153,1.700000,1.3,2.1,2.1,2,1
1,30000646,1.600000,1.6,1.6,1.6,2,1
2,30001148,1.500000,1.5,1.5,1.5,1,1
3,30001336,NaN,NaN,NaN,NaN,0,0
4,30001396,136.266667,1.8,220.0,220.0,3,1

In [40]:
df_sparse_agg = df_sparse_agg.merge(lactate_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,map_max,map_last,map_count,map_measured,lactate_mean,lactate_min,lactate_max,lactate_last,lactate_count,lactate_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,8.0,6.0,3,1,1.700000,1.3,2.1,2.1,2,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,NaN,NaN,0,0,1.600000,1.6,1.6,1.6,2,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,7.0,7.0,2,1,1.500000,1.5,1.5,1.5,1,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,NaN,NaN,0,0,136.266667,1.8,220.0,220.0,3,1

In [41]:
# aggregating creatinine

creatinine_agg = df_ts_window.groupby("stay_id")["creatinine"].agg(
    creatinine_mean="mean",
    creatinine_min="min",
    creatinine_max="max",
    creatinine_last="last",
    creatinine_count="count"
).reset_index()

creatinine_agg.head()

,stay_id,creatinine_mean,creatinine_min,creatinine_max,creatinine_last,creatinine_count
0,30000153,1.000000,0.9,1.1,1.1,2
1,30000646,0.833333,0.6,1.0,0.6,3
2,30001148,0.600000,0.6,0.6,0.6,2
3,30001336,1.033333,1.0,1.1,1.0,3
4,30001396,1.350000,1.1,1.6,1.6,2

In [42]:
creatinine_agg["creatinine_measured"] = (creatinine_agg["creatinine_count"] > 0).astype(int)

creatinine_agg.head()

,stay_id,creatinine_mean,creatinine_min,creatinine_max,creatinine_last,creatinine_count,creatinine_measured
0,30000153,1.000000,0.9,1.1,1.1,2,1
1,30000646,0.833333,0.6,1.0,0.6,3,1
2,30001148,0.600000,0.6,0.6,0.6,2,1
3,30001336,1.033333,1.0,1.1,1.0,3,1
4,30001396,1.350000,1.1,1.6,1.6,2,1

In [43]:
df_sparse_agg = df_sparse_agg.merge(creatinine_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,lactate_max,lactate_last,lactate_count,lactate_measured,creatinine_mean,creatinine_min,creatinine_max,creatinine_last,creatinine_count,creatinine_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,2.1,2.1,2,1,1.000000,0.9,1.1,1.1,2,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,1.6,1.6,2,1,0.833333,0.6,1.0,0.6,3,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,1.5,1.5,1,1,0.600000,0.6,0.6,0.6,2,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,NaN,NaN,0,0,1.033333,1.0,1.1,1.0,3,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,220.0,220.0,3,1,1.350000,1.1,1.6,1.6,2,1

In [44]:
# aggregating bilirubin

bilirubin_agg = df_ts_window.groupby("stay_id")["bilirubin"].agg(
    bilirubin_mean="mean",
    bilirubin_min="min",
    bilirubin_max="max",
    bilirubin_last="last",
    bilirubin_count="count"
).reset_index()

bilirubin_agg.head()

,stay_id,bilirubin_mean,bilirubin_min,bilirubin_max,bilirubin_last,bilirubin_count
0,30000153,NaN,NaN,NaN,NaN,0
1,30000646,0.70,0.7,0.7,0.7,1
2,30001148,NaN,NaN,NaN,NaN,0
3,30001336,0.90,0.9,0.9,0.9,2
4,30001396,0.55,0.5,0.6,0.5,2

In [45]:
bilirubin_agg["bilirubin_measured"] = (bilirubin_agg["bilirubin_count"] > 0).astype(int)

bilirubin_agg.head()

,stay_id,bilirubin_mean,bilirubin_min,bilirubin_max,bilirubin_last,bilirubin_count,bilirubin_measured
0,30000153,NaN,NaN,NaN,NaN,0,0
1,30000646,0.70,0.7,0.7,0.7,1,1
2,30001148,NaN,NaN,NaN,NaN,0,0
3,30001336,0.90,0.9,0.9,0.9,2,1
4,30001396,0.55,0.5,0.6,0.5,2,1

In [46]:
df_sparse_agg = df_sparse_agg.merge(bilirubin_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,creatinine_max,creatinine_last,creatinine_count,creatinine_measured,bilirubin_mean,bilirubin_min,bilirubin_max,bilirubin_last,bilirubin_count,bilirubin_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,1.1,1.1,2,1,NaN,NaN,NaN,NaN,0,0
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,1.0,0.6,3,1,0.70,0.7,0.7,0.7,1,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,0.6,0.6,2,1,NaN,NaN,NaN,NaN,0,0
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,1.1,1.0,3,1,0.90,0.9,0.9,0.9,2,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,1.6,1.6,2,1,0.55,0.5,0.6,0.5,2,1

In [47]:
# aggregating platelets

platelets_agg = df_ts_window.groupby("stay_id")["platelets"].agg(
    platelets_mean="mean",
    platelets_min="min",
    platelets_max="max",
    platelets_last="last",
    platelets_count="count"
).reset_index()

platelets_agg.head()

,stay_id,platelets_mean,platelets_min,platelets_max,platelets_last,platelets_count
0,30000153,167.500000,162.0,173.0,162.0,2
1,30000646,290.333333,266.0,337.0,266.0,3
2,30001148,178.333333,160.0,198.0,198.0,3
3,30001336,162.500000,162.0,163.0,162.0,2
4,30001396,214.500000,210.0,219.0,210.0,2

In [48]:
platelets_agg["platelets_measured"] = (platelets_agg["platelets_count"] > 0).astype(int)

platelets_agg.head()

,stay_id,platelets_mean,platelets_min,platelets_max,platelets_last,platelets_count,platelets_measured
0,30000153,167.500000,162.0,173.0,162.0,2,1
1,30000646,290.333333,266.0,337.0,266.0,3,1
2,30001148,178.333333,160.0,198.0,198.0,3,1
3,30001336,162.500000,162.0,163.0,162.0,2,1
4,30001396,214.500000,210.0,219.0,210.0,2,1

In [49]:
df_sparse_agg = df_sparse_agg.merge(platelets_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,bilirubin_max,bilirubin_last,bilirubin_count,bilirubin_measured,platelets_mean,platelets_min,platelets_max,platelets_last,platelets_count,platelets_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,NaN,NaN,0,0,167.500000,162.0,173.0,162.0,2,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,0.7,0.7,1,1,290.333333,266.0,337.0,266.0,3,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,NaN,NaN,0,0,178.333333,160.0,198.0,198.0,3,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,0.9,0.9,2,1,162.500000,162.0,163.0,162.0,2,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,0.6,0.5,2,1,214.500000,210.0,219.0,210.0,2,1

In [50]:
# aggregating white blood cells (wbc)

wbc_agg = df_ts_window.groupby("stay_id")["wbc"].agg(
    wbc_mean="mean",
    wbc_min="min",
    wbc_max="max",
    wbc_last="last",
    wbc_count="count"
).reset_index()

wbc_agg

        stay_id  wbc_mean  wbc_min  wbc_max  wbc_last  wbc_count
0      30000153       NaN      NaN      NaN       NaN          0
1      30000646       NaN      NaN      NaN       NaN          0
2      30001148       NaN      NaN      NaN       NaN          0
3      30001336       NaN      NaN      NaN       NaN          0
4      30001396       NaN      NaN      NaN       NaN          0
...         ...       ...      ...      ...       ...        ...
40452  39999172       NaN      NaN      NaN       NaN          0
40453  39999230       3.0      3.0      3.0       3.0          1
40454  39999286       NaN      NaN      NaN       NaN          0
40455  39999384       NaN      NaN      NaN       NaN          0
40456  39999552       NaN      NaN      NaN       NaN          0

[40457 rows x 6 columns]

In [51]:
wbc_agg["wbc_measured"] = (wbc_agg["wbc_count"] > 0).astype(int)

wbc_agg.head()

    stay_id  wbc_mean  wbc_min  wbc_max  wbc_last  wbc_count  wbc_measured
0  30000153       NaN      NaN      NaN       NaN          0             0
1  30000646       NaN      NaN      NaN       NaN          0             0
2  30001148       NaN      NaN      NaN       NaN          0             0
3  30001336       NaN      NaN      NaN       NaN          0             0
4  30001396       NaN      NaN      NaN       NaN          0             0

In [52]:
df_sparse_agg = df_sparse_agg.merge(wbc_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,platelets_max,platelets_last,platelets_count,platelets_measured,wbc_mean,wbc_min,wbc_max,wbc_last,wbc_count,wbc_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,173.0,162.0,2,1,NaN,NaN,NaN,NaN,0,0
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,337.0,266.0,3,1,NaN,NaN,NaN,NaN,0,0
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,198.0,198.0,3,1,NaN,NaN,NaN,NaN,0,0
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,163.0,162.0,2,1,NaN,NaN,NaN,NaN,0,0
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,219.0,210.0,2,1,NaN,NaN,NaN,NaN,0,0

In [53]:
# aggregating sodium

sodium_agg = df_ts_window.groupby("stay_id")["sodium"].agg(
    sodium_mean="mean",
    sodium_min="min",
    sodium_max="max",
    sodium_last="last",
    sodium_count="count"
).reset_index()

sodium_agg.head()

    stay_id  sodium_mean  sodium_min  sodium_max  sodium_last  sodium_count
0  30000153   142.500000       141.0       145.0        145.0             4
1  30000646   140.666667       138.0       143.0        143.0             3
2  30001148   135.666667       133.0       138.0        138.0             3
3  30001336   132.666667       131.0       134.0        134.0             3
4  30001396   141.000000       140.0       142.0        140.0             2

In [54]:
sodium_agg["sodium_measured"] = (sodium_agg["sodium_count"] > 0).astype(int)

sodium_agg.head()

,stay_id,sodium_mean,sodium_min,sodium_max,sodium_last,sodium_count,sodium_measured
0,30000153,142.500000,141.0,145.0,145.0,4,1
1,30000646,140.666667,138.0,143.0,143.0,3,1
2,30001148,135.666667,133.0,138.0,138.0,3,1
3,30001336,132.666667,131.0,134.0,134.0,3,1
4,30001396,141.000000,140.0,142.0,140.0,2,1

In [55]:
df_sparse_agg = df_sparse_agg.merge(sodium_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,wbc_max,wbc_last,wbc_count,wbc_measured,sodium_mean,sodium_min,sodium_max,sodium_last,sodium_count,sodium_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,NaN,NaN,0,0,142.500000,141.0,145.0,145.0,4,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,NaN,NaN,0,0,140.666667,138.0,143.0,143.0,3,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,NaN,NaN,0,0,135.666667,133.0,138.0,138.0,3,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,NaN,NaN,0,0,132.666667,131.0,134.0,134.0,3,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,NaN,NaN,0,0,141.000000,140.0,142.0,140.0,2,1

In [56]:
# aggregating blood urea nitrogen (bun)

bun_agg = df_ts_window.groupby("stay_id")["bun"].agg(
    bun_mean="mean",
    bun_min="min",
    bun_max="max",
    bun_last="last",
    bun_count="count"
).reset_index()

bun_agg.head()

    stay_id   bun_mean  bun_min  bun_max  bun_last  bun_count
0  30000153  22.000000     22.0     22.0      22.0          2
1  30000646  11.000000      9.0     12.0       9.0          3
2  30001148  10.500000      9.0     12.0      12.0          2
3  30001336  17.666667     17.0     19.0      19.0          3
4  30001396  19.500000     17.0     22.0      22.0          2

In [57]:
bun_agg["bun_measured"] = (bun_agg["bun_count"] > 0).astype(int)

bun_agg.head()

    stay_id   bun_mean  bun_min  bun_max  bun_last  bun_count  bun_measured
0  30000153  22.000000     22.0     22.0      22.0          2             1
1  30000646  11.000000      9.0     12.0       9.0          3             1
2  30001148  10.500000      9.0     12.0      12.0          2             1
3  30001336  17.666667     17.0     19.0      19.0          3             1
4  30001396  19.500000     17.0     22.0      22.0          2             1

In [58]:
df_sparse_agg = df_sparse_agg.merge(bun_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,sodium_max,sodium_last,sodium_count,sodium_measured,bun_mean,bun_min,bun_max,bun_last,bun_count,bun_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,145.0,145.0,4,1,22.000000,22.0,22.0,22.0,2,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,143.0,143.0,3,1,11.000000,9.0,12.0,9.0,3,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,138.0,138.0,3,1,10.500000,9.0,12.0,12.0,2,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,134.0,134.0,3,1,17.666667,17.0,19.0,19.0,3,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,142.0,140.0,2,1,19.500000,17.0,22.0,22.0,2,1

In [59]:
# aggregating vasopressor dose

vasopressor_agg = df_ts_window.groupby("stay_id")["vasopressor_dose"].agg(
    vasopressor_dose_mean="mean",
    vasopressor_dose_min="min",
    vasopressor_dose_max="max",
    vasopressor_dose_last="last",
    vasopressor_dose_count="count"
).reset_index()

vasopressor_agg.head()

,stay_id,vasopressor_dose_mean,vasopressor_dose_min,vasopressor_dose_max,vasopressor_dose_last,vasopressor_dose_count
0,30000153,NaN,NaN,NaN,NaN,0
1,30000646,6.559329,0.458355,27.562899,0.458355,5
2,30001148,1.147795,0.157687,2.497262,2.497262,3
3,30001336,NaN,NaN,NaN,NaN,0
4,30001396,NaN,NaN,NaN,NaN,0

In [60]:
vasopressor_agg["vasopressor_dose_measured"] = (vasopressor_agg["vasopressor_dose_count"] > 0).astype(int)

vasopressor_agg.head()

,stay_id,vasopressor_dose_mean,vasopressor_dose_min,vasopressor_dose_max,vasopressor_dose_last,vasopressor_dose_count,vasopressor_dose_measured
0,30000153,NaN,NaN,NaN,NaN,0,0
1,30000646,6.559329,0.458355,27.562899,0.458355,5,1
2,30001148,1.147795,0.157687,2.497262,2.497262,3,1
3,30001336,NaN,NaN,NaN,NaN,0,0
4,30001396,NaN,NaN,NaN,NaN,0,0

In [61]:
df_sparse_agg = df_sparse_agg.merge(vasopressor_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,bun_max,bun_last,bun_count,bun_measured,vasopressor_dose_mean,vasopressor_dose_min,vasopressor_dose_max,vasopressor_dose_last,vasopressor_dose_count,vasopressor_dose_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,22.0,22.0,2,1,NaN,NaN,NaN,NaN,0,0
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,12.0,9.0,3,1,6.559329,0.458355,27.562899,0.458355,5,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,12.0,12.0,2,1,1.147795,0.157687,2.497262,2.497262,3,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,19.0,19.0,3,1,NaN,NaN,NaN,NaN,0,0
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,22.0,22.0,2,1,NaN,NaN,NaN,NaN,0,0

In [62]:
# aggregating fluid input

fluid_agg = df_ts_window.groupby("stay_id")["fluid_input"].agg(
    fluid_input_mean="mean",
    fluid_input_min="min",
    fluid_input_max="max",
    fluid_input_last="last",
    fluid_input_count="count"
).reset_index()

fluid_agg

,stay_id,fluid_input_mean,fluid_input_min,fluid_input_max,fluid_input_last,fluid_input_count
0,30000153,NaN,NaN,NaN,NaN,0
1,30000646,NaN,NaN,NaN,NaN,0
2,30001148,NaN,NaN,NaN,NaN,0
3,30001336,NaN,NaN,NaN,NaN,0
4,30001396,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...
40452,39999172,NaN,NaN,NaN,NaN,0
40453,39999230,149.999996,99.999998,199.999995,99.999998,2
40454,39999286,NaN,NaN,NaN,NaN,0
40455,39999384,NaN,NaN,NaN,NaN,0
40456,39999552,249.999990,249.999990,249.999990,249.999990,3

In [63]:
fluid_agg["fluid_input_measured"] = (fluid_agg["fluid_input_count"] > 0).astype(int)

fluid_agg

,stay_id,fluid_input_mean,fluid_input_min,fluid_input_max,fluid_input_last,fluid_input_count,fluid_input_measured
0,30000153,NaN,NaN,NaN,NaN,0,0
1,30000646,NaN,NaN,NaN,NaN,0,0
2,30001148,NaN,NaN,NaN,NaN,0,0
3,30001336,NaN,NaN,NaN,NaN,0,0
4,30001396,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...
40452,39999172,NaN,NaN,NaN,NaN,0,0
40453,39999230,149.999996,99.999998,199.999995,99.999998,2,1
40454,39999286,NaN,NaN,NaN,NaN,0,0
40455,39999384,NaN,NaN,NaN,NaN,0,0
40456,39999552,249.999990,249.999990,249.999990,249.999990,3,1

In [64]:
df_sparse_agg = df_sparse_agg.merge(fluid_agg, on="stay_id", how="left")

df_sparse_agg

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,vasopressor_dose_max,vasopressor_dose_last,vasopressor_dose_count,vasopressor_dose_measured,fluid_input_mean,fluid_input_min,fluid_input_max,fluid_input_last,fluid_input_count,fluid_input_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,27.562899,0.458355,5,1,NaN,NaN,NaN,NaN,0,0
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,2.497262,2.497262,3,1,NaN,NaN,NaN,NaN,0,0
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40452,39999172,4.000000,4.0,4.0,4.0,5,1,96.840000,96.0,97.8,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
40453,39999230,4.000000,4.0,4.0,4.0,6,1,98.200000,97.1,99.2,...,2.535743,2.430573,11,1,149.999996,99.999998,199.999995,99.999998,2,1
40454,39999286,4.000000,4.0,4.0,4.0,4,1,98.205000,97.2,98.9,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
40455,39999384,4.000000,4.0,4.0,4.0,6,1,97.933333,97.5,98.4,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
40456,39999552,2.250000,1.0,4.0,4.0,4,1,98.200000,98.2,98.2,...,1.135484,1.135484,3,1,249.999990,249.999990,249.999990,249.999990,3,1

In [65]:
# aggregating sofa respiratory score (sofa_resp)

sofa_resp_agg = df_ts_window.groupby("stay_id")["sofa_resp"].agg(
    sofa_resp_mean="mean", sofa_resp_min="min", sofa_resp_max="max",
    sofa_resp_last="last", sofa_resp_count="count"
).reset_index()

sofa_resp_agg.head()

,stay_id,sofa_resp_mean,sofa_resp_min,sofa_resp_max,sofa_resp_last,sofa_resp_count
0,30000153,0.00,0.0,0.0,0.0,3
1,30000646,2.00,2.0,2.0,2.0,1
2,30001148,0.75,0.0,1.0,0.0,4
3,30001336,NaN,NaN,NaN,NaN,0
4,30001396,NaN,NaN,NaN,NaN,0

In [66]:
sofa_resp_agg["sofa_resp_measured"] = (sofa_resp_agg["sofa_resp_count"] > 0).astype(int)

sofa_resp_agg.head()

,stay_id,sofa_resp_mean,sofa_resp_min,sofa_resp_max,sofa_resp_last,sofa_resp_count,sofa_resp_measured
0,30000153,0.00,0.0,0.0,0.0,3,1
1,30000646,2.00,2.0,2.0,2.0,1,1
2,30001148,0.75,0.0,1.0,0.0,4,1
3,30001336,NaN,NaN,NaN,NaN,0,0
4,30001396,NaN,NaN,NaN,NaN,0,0

In [67]:
df_sparse_agg = df_sparse_agg.merge(sofa_resp_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,fluid_input_max,fluid_input_last,fluid_input_count,fluid_input_measured,sofa_resp_mean,sofa_resp_min,sofa_resp_max,sofa_resp_last,sofa_resp_count,sofa_resp_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,NaN,NaN,0,0,0.00,0.0,0.0,0.0,3,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,NaN,NaN,0,0,2.00,2.0,2.0,2.0,1,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,NaN,NaN,0,0,0.75,0.0,1.0,0.0,4,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0

In [68]:
# aggregating sofa renal score (sofa_renal)

sofa_renal_agg = df_ts_window.groupby("stay_id")["sofa_renal"].agg(
    sofa_renal_mean="mean", sofa_renal_min="min", sofa_renal_max="max",
    sofa_renal_last="last", sofa_renal_count="count"
).reset_index()

sofa_renal_agg.head()

,stay_id,sofa_renal_mean,sofa_renal_min,sofa_renal_max,sofa_renal_last,sofa_renal_count
0,30000153,0.000000,0.0,0.0,0.0,4
1,30000646,0.000000,0.0,0.0,0.0,3
2,30001148,0.000000,0.0,0.0,0.0,2
3,30001336,0.000000,0.0,0.0,0.0,5
4,30001396,0.333333,0.0,1.0,0.0,3

In [69]:
sofa_renal_agg["sofa_renal_measured"] = (sofa_renal_agg["sofa_renal_count"] > 0).astype(int)

sofa_renal_agg.head()

,stay_id,sofa_renal_mean,sofa_renal_min,sofa_renal_max,sofa_renal_last,sofa_renal_count,sofa_renal_measured
0,30000153,0.000000,0.0,0.0,0.0,4,1
1,30000646,0.000000,0.0,0.0,0.0,3,1
2,30001148,0.000000,0.0,0.0,0.0,2,1
3,30001336,0.000000,0.0,0.0,0.0,5,1
4,30001396,0.333333,0.0,1.0,0.0,3,1

In [70]:
df_sparse_agg = df_sparse_agg.merge(sofa_renal_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,sofa_resp_max,sofa_resp_last,sofa_resp_count,sofa_resp_measured,sofa_renal_mean,sofa_renal_min,sofa_renal_max,sofa_renal_last,sofa_renal_count,sofa_renal_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,0.0,0.0,3,1,0.000000,0.0,0.0,0.0,4,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,2.0,2.0,1,1,0.000000,0.0,0.0,0.0,3,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,1.0,0.0,4,1,0.000000,0.0,0.0,0.0,2,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,NaN,NaN,0,0,0.000000,0.0,0.0,0.0,5,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,NaN,NaN,0,0,0.333333,0.0,1.0,0.0,3,1

In [71]:
# aggregating sofa liver score (sofa_liver)

sofa_liver_agg = df_ts_window.groupby("stay_id")["sofa_liver"].agg(
    sofa_liver_mean="mean", sofa_liver_min="min", sofa_liver_max="max",
    sofa_liver_last="last", sofa_liver_count="count"
).reset_index()

sofa_liver_agg.head()

,stay_id,sofa_liver_mean,sofa_liver_min,sofa_liver_max,sofa_liver_last,sofa_liver_count
0,30000153,NaN,NaN,NaN,NaN,0
1,30000646,0.0,0.0,0.0,0.0,1
2,30001148,NaN,NaN,NaN,NaN,0
3,30001336,0.0,0.0,0.0,0.0,2
4,30001396,0.0,0.0,0.0,0.0,2

In [72]:
sofa_liver_agg["sofa_liver_measured"] = (sofa_liver_agg["sofa_liver_count"] > 0).astype(int)

sofa_liver_agg.head()

,stay_id,sofa_liver_mean,sofa_liver_min,sofa_liver_max,sofa_liver_last,sofa_liver_count,sofa_liver_measured
0,30000153,NaN,NaN,NaN,NaN,0,0
1,30000646,0.0,0.0,0.0,0.0,1,1
2,30001148,NaN,NaN,NaN,NaN,0,0
3,30001336,0.0,0.0,0.0,0.0,2,1
4,30001396,0.0,0.0,0.0,0.0,2,1

In [73]:
df_sparse_agg = df_sparse_agg.merge(sofa_liver_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,sofa_renal_max,sofa_renal_last,sofa_renal_count,sofa_renal_measured,sofa_liver_mean,sofa_liver_min,sofa_liver_max,sofa_liver_last,sofa_liver_count,sofa_liver_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,0.0,0.0,4,1,NaN,NaN,NaN,NaN,0,0
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,0.0,0.0,3,1,0.0,0.0,0.0,0.0,1,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,0.0,0.0,2,1,NaN,NaN,NaN,NaN,0,0
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,0.0,0.0,5,1,0.0,0.0,0.0,0.0,2,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,1.0,0.0,3,1,0.0,0.0,0.0,0.0,2,1

In [74]:
# aggregating sofa coagulation score (sofa_coag)

sofa_coag_agg = df_ts_window.groupby("stay_id")["sofa_coag"].agg(
    sofa_coag_mean="mean", sofa_coag_min="min", sofa_coag_max="max",
    sofa_coag_last="last", sofa_coag_count="count"
).reset_index()

sofa_coag_agg.head()

,stay_id,sofa_coag_mean,sofa_coag_min,sofa_coag_max,sofa_coag_last,sofa_coag_count
0,30000153,0.0,0.0,0.0,0.0,2
1,30000646,0.0,0.0,0.0,0.0,3
2,30001148,0.0,0.0,0.0,0.0,2
3,30001336,0.0,0.0,0.0,0.0,2
4,30001396,0.0,0.0,0.0,0.0,2

In [75]:
sofa_coag_agg["sofa_coag_measured"] = (sofa_coag_agg["sofa_coag_count"] > 0).astype(int)

sofa_coag_agg.head()

,stay_id,sofa_coag_mean,sofa_coag_min,sofa_coag_max,sofa_coag_last,sofa_coag_count,sofa_coag_measured
0,30000153,0.0,0.0,0.0,0.0,2,1
1,30000646,0.0,0.0,0.0,0.0,3,1
2,30001148,0.0,0.0,0.0,0.0,2,1
3,30001336,0.0,0.0,0.0,0.0,2,1
4,30001396,0.0,0.0,0.0,0.0,2,1

In [76]:
df_sparse_agg = df_sparse_agg.merge(sofa_coag_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,sofa_liver_max,sofa_liver_last,sofa_liver_count,sofa_liver_measured,sofa_coag_mean,sofa_coag_min,sofa_coag_max,sofa_coag_last,sofa_coag_count,sofa_coag_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,NaN,NaN,0,0,0.0,0.0,0.0,0.0,2,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,0.0,0.0,1,1,0.0,0.0,0.0,0.0,3,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,NaN,NaN,0,0,0.0,0.0,0.0,0.0,2,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,0.0,0.0,2,1,0.0,0.0,0.0,0.0,2,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,0.0,0.0,2,1,0.0,0.0,0.0,0.0,2,1

In [77]:
# aggregating sofa central nervous system score (sofa_cns)

sofa_cns_agg = df_ts_window.groupby("stay_id")["sofa_cns"].agg(
    sofa_cns_mean="mean", sofa_cns_min="min", sofa_cns_max="max",
    sofa_cns_last="last", sofa_cns_count="count"
).reset_index()

sofa_cns_agg.head()

,stay_id,sofa_cns_mean,sofa_cns_min,sofa_cns_max,sofa_cns_last,sofa_cns_count
0,30000153,1.200000,0.0,3.0,1.0,15
1,30000646,0.000000,0.0,0.0,0.0,4
2,30001148,0.714286,0.0,4.0,0.0,7
3,30001336,0.000000,0.0,0.0,0.0,3
4,30001396,0.500000,0.0,1.0,0.0,6

In [78]:
sofa_cns_agg["sofa_cns_measured"] = (sofa_cns_agg["sofa_cns_count"] > 0).astype(int)

sofa_cns_agg.head()

,stay_id,sofa_cns_mean,sofa_cns_min,sofa_cns_max,sofa_cns_last,sofa_cns_count,sofa_cns_measured
0,30000153,1.200000,0.0,3.0,1.0,15,1
1,30000646,0.000000,0.0,0.0,0.0,4,1
2,30001148,0.714286,0.0,4.0,0.0,7,1
3,30001336,0.000000,0.0,0.0,0.0,3,1
4,30001396,0.500000,0.0,1.0,0.0,6,1

In [79]:
#all together in for sparse variables

df_sparse_agg = df_sparse_agg.merge(sofa_cns_agg, on="stay_id", how="left")

df_sparse_agg.head()

,stay_id,gcs_mean,gcs_min,gcs_max,gcs_last,gcs_count,gcs_measured,temp_mean,temp_min,temp_max,...,sofa_coag_max,sofa_coag_last,sofa_coag_count,sofa_coag_measured,sofa_cns_mean,sofa_cns_min,sofa_cns_max,sofa_cns_last,sofa_cns_count,sofa_cns_measured
0,30000153,2.647059,1.0,4.0,4.0,17,1,99.162500,96.8,100.8,...,0.0,0.0,2,1,1.200000,0.0,3.0,1.0,15,1
1,30000646,4.000000,4.0,4.0,4.0,4,1,99.200000,97.8,102.4,...,0.0,0.0,3,1,0.000000,0.0,0.0,0.0,4,1
2,30001148,2.833333,1.0,4.0,4.0,6,1,97.500000,95.6,100.7,...,0.0,0.0,2,1,0.714286,0.0,4.0,0.0,7,1
3,30001336,4.000000,4.0,4.0,4.0,3,1,98.342857,98.1,98.5,...,0.0,0.0,2,1,0.000000,0.0,0.0,0.0,3,1
4,30001396,3.500000,3.0,4.0,4.0,6,1,99.371429,97.3,101.9,...,0.0,0.0,2,1,0.500000,0.0,1.0,0.0,6,1

In [80]:
#checking final shape of sparse aggregated dataframe

df_sparse_agg.shape

(40457, 103)

In [81]:
# merging dense and sparse aggregations 

df_ts_agg = df_dense_agg.merge(df_sparse_agg, on="stay_id", how="left")

df_ts_agg

,stay_id,hr_mean,hr_min,hr_max,hr_std,hr_last,hr_count,hr_slope,hr_measured,rr_mean,...,sofa_coag_max,sofa_coag_last,sofa_coag_count,sofa_coag_measured,sofa_cns_mean,sofa_cns_min,sofa_cns_max,sofa_cns_last,sofa_cns_count,sofa_cns_measured
0,30000153,106.040000,83.0,128.0,12.084701,90.0,25,0.093846,1,15.020000,...,0.0,0.0,2,1,1.200000,0.0,3.0,1.0,15,1
1,30000646,84.090000,69.0,102.0,9.619013,80.5,25,-0.587308,1,23.037619,...,0.0,0.0,3,1,0.000000,0.0,0.0,0.0,4,1
2,30001148,74.909091,64.0,80.0,5.639226,64.0,22,-0.635799,1,15.083333,...,0.0,0.0,2,1,0.714286,0.0,4.0,0.0,7,1
3,30001336,63.041667,53.0,73.0,5.689267,68.0,24,0.273913,1,25.820000,...,0.0,0.0,2,1,0.000000,0.0,0.0,0.0,3,1
4,30001396,83.583333,74.0,93.0,4.262237,85.0,24,0.055652,1,22.708333,...,0.0,0.0,2,1,0.500000,0.0,1.0,0.0,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40452,39999172,61.200000,60.0,69.0,2.273030,60.0,25,-0.018462,1,13.760000,...,0.0,0.0,1,1,0.000000,0.0,0.0,0.0,5,1
40453,39999230,105.280000,98.0,118.0,5.711976,103.0,25,-0.536154,1,18.600000,...,0.0,0.0,2,1,0.000000,0.0,0.0,0.0,6,1
40454,39999286,101.800000,81.0,127.0,13.231906,97.0,25,-1.466923,1,17.880000,...,1.0,1.0,3,1,0.000000,0.0,0.0,0.0,4,1
40455,39999384,70.760870,63.0,80.0,3.854954,76.0,23,0.273221,1,18.239130,...,0.0,0.0,2,1,0.000000,0.0,0.0,0.0,7,1
40456,39999552,85.239130,63.5,107.0,12.216670,74.0,23,0.115613,1,16.804348,...,0.0,0.0,2,1,1.250000,0.0,4.0,0.0,4,1

In [82]:
# exporting time series aggregated features
# Reference: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

df_ts_agg.to_csv("cohort_step4.csv", index=False)